* Create arrays with all the data types available in numpy
    * integer
    * boolean
    * unsigned integer
    * float
    * complex float
    * timedelta
    * datetime
    * object
    * string
    * unicode string
    * fixed chunk of memory for other type ( void )

In [1]:
#integer
import numpy as np
x = np.array([10,20,30,40,50])
print(x)
x.dtype

[10 20 30 40 50]


dtype('int32')

In [2]:
#boolean
import numpy as np

x = np.array([1,2,3,4,5], dtype='bool_')
print(x)
x.dtype

[ True  True  True  True  True]


dtype('bool')

In [3]:
#unsigned integer
import numpy as np
x= np.array([65535], dtype='uint16')
print(x)
x.dtype



[65535]


dtype('uint16')

In [4]:
#float
import numpy as np
x= np.array([1.2, 42.42,33.33,7.8,9.67])
print(x)
x.dtype


[ 1.2  42.42 33.33  7.8   9.67]


dtype('float64')

In [5]:
#complex float
import numpy as np

x = np.array([10.55,1 + 12j,50.33j])
print(x)
x.dtype

[10.55 +0.j    1.  +12.j    0.  +50.33j]


dtype('complex128')

In [6]:
#timedelta
import numpy as np
x=np.timedelta64(10, 'M')
print(x)

10 months


In [7]:
#datetime
import numpy as np
x=np.array(['2010-07-11', '2006-01-13', '2010-08-13'], dtype='datetime64')
x

array(['2010-07-11', '2006-01-13', '2010-08-13'], dtype='datetime64[D]')

In [8]:
#object
import numpy as np
x = np.array([100,45,79], dtype='O')
x


array([100, 45, 79], dtype=object)

In [9]:
#String
import numpy as np
x = np.array(['Srm', 'University', 'Amaravati'])
print(x)
x.dtype

['Srm' 'University' 'Amaravati']


dtype('<U10')

In [10]:
#unicode string
import numpy as np
x = np.array([u'\u03bcm', u'\u2202r', u'\u2206\u03bb'], dtype='U')
x

array(['μm', '∂r', '∆λ'], dtype='<U2')

In [11]:
#void
import numpy as np
x=np.void([], dtype='V')
x

array([], dtype='|V8')